package com.faforever.client.stats.domain;

public enum UnitCategory {
  AIR, LAND, NAVAL, ENGINEER, ARTILLERY, ANTIAIR, TRANSPORTATION, STRUCTURE, FACTORY, ENERGYPRODUCTION, MASSPRODUCTION,
  DEFENSE, TECH1, TECH2, TECH3
}
