changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - "*"
      exclude:
        authors:
          - "dependabot"
    - title: Dependency Updates
      labels:
        - dependencies
