faf-client:
  server:
    host: localhost

  irc:
    host: localhost

  vault:
    base-url: https://content.faforever.com
    replay-download-url-format: https://replay.faforever.com/%s

  news:
    feed-url: https://direct.faforever.com/news/feed

  replay:
    remote-host: localhost

  website:
    base-url: http://localhost:8020

  api:
    base-url: http://localhost:8010
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: https://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

logging:
  level:
    org.pircbotx.PircBotX: off
    com.faforever.client.chat.PircBotXChatService: off
    com.faforever.client.fa.relay.ice: debug
