package com.faforever.client.patch;

public enum UpdateServerMessageType {
  PATH_TO_SIM_MOD,
  SIM_MOD_NOT_FOUND,
  LIST_FILES_TO_UP,
  UNKNOWN_APP,
  VERSION_PATCH_NOT_FOUND,
  VERSION_MOD_PATCH_NOT_FOUND,
  PATCH_NOT_FOUND,
  UP_TO_DATE,
  ERROR_FILE,
  SEND_FILE_PATH,
  SEND_PATCH_URL,
}
