package com.faforever.client.filter;

public enum FilterName {
  GAME_TYPE,
  PRIVATE_GAME,
  SIM_MODS,
  MAP_FOLDER_NAME_BLACKLIST,
  PLAYER_NAME,
  GAME_STATUS,
  PLAYER_RATING,
  CLAN,
  COUNTRY_CODE,
  MAP_NAME,
  MAP_HEIGHT,
  MAP_WIDTH,
  FEATURE_MOD,
  NUMBER_OF_PLAYERS,
  ONE_PLAYER,
  GAME_WITH_FRIENDS,
}
